#!/data/data/com.termux/files/usr/bin/bash
set -Eeuo pipefail

# Packages to install during bootstrap. Adjust as needed before running the script.
PACKAGES=(
  bash-completion
  bat
  curl
  gh
  git
  gnupg
  golang
  htop
  jq
  mc
  micro
  mosh
  neovim
  nodejs
  nmap
  openssh
  python
  ripgrep
  rsync
  dnsutils
  telnet
  tmux
  tree
  whois
  unzip
  wget
  yq
  yt-dlp
  zip
)

FONT_URL="https://github.com/JetBrains/JetBrainsMono/raw/master/fonts/ttf/JetBrainsMono-Regular.ttf"
TERMUX_PROPERTIES_PATH="$HOME/.termux/termux.properties"
TERMUX_COLORS_PATH="$HOME/.termux/colors.properties"
FONT_DEST="$HOME/.termux/font.ttf"
PROFILE_PATH="$HOME/.profile"
GITCONFIG_PATH="$HOME/.gitconfig"
INPUTRC_PATH="$HOME/.inputrc"
BASHRC_PATH="$HOME/.bashrc"
TMUX_CONF_PATH="$HOME/.tmux.conf"
SSH_CONFIG_PATH="$HOME/.ssh/config"

# User credentials (will be set interactively)
USER_FULLNAME=""
USER_EMAIL=""
USER_SSH_USER=""

trap 'printf "[error] line %s: %s\n" "$LINENO" "$BASH_COMMAND" >&2' ERR

log() {
  printf '[setup] %s\n' "$1"
}

warn() {
  printf '[warn] %s\n' "$1" >&2
}

prompt_user_info() {
  log 'Please provide your information for Git and SSH configuration.'

  printf 'Full name (for Git commits): '
  read -r USER_FULLNAME

  printf 'Email (for Git commits): '
  read -r USER_EMAIL

  printf 'SSH username (for remote logins): '
  read -r USER_SSH_USER

  if [ -z "$USER_FULLNAME" ] || [ -z "$USER_EMAIL" ] || [ -z "$USER_SSH_USER" ]; then
    warn 'Some fields were left empty. Using defaults where needed.'
  fi
}

require_termux() {
  if [ -z "${PREFIX:-}" ] || [ ! -x "$PREFIX/bin/pkg" ]; then
    warn 'This script is intended to run inside Termux.'
    exit 1
  fi
}

run_pkg() {
  "$PREFIX/bin/pkg" "$@"
}

setup_storage() {
  if [ ! -d "$HOME/storage" ]; then
    log 'Requesting storage permissions via termux-setup-storage...'
    termux-setup-storage || warn 'termux-setup-storage failed or was skipped.'
  else
    log 'Shared storage already available; skipping termux-setup-storage.'
  fi
}

update_system() {
  log 'Updating package repositories...'
  run_pkg update -y
  log 'Upgrading installed packages...'
  run_pkg upgrade -y
}

install_packages() {
  log 'Installing requested packages...'
  for pkg in "${PACKAGES[@]}"; do
    if dpkg -s "$pkg" >/dev/null 2>&1; then
      log "- $pkg already installed"
    else
      log "- installing $pkg"
      run_pkg install -y "$pkg"
    fi
  done
}

write_file_if_different() {
  local target="$1"
  local tmp
  tmp=$(mktemp)
  cat > "$tmp"

  local changed=1
  if [ -f "$target" ] && command -v cmp >/dev/null 2>&1; then
    if cmp -s "$tmp" "$target"; then
      changed=0
    fi
  fi

  mkdir -p "$(dirname "$target")"
  if [ "$changed" -eq 1 ]; then
    mv "$tmp" "$target"
    log "Updated ${target/#$HOME/~/}"
  else
    rm -f "$tmp"
    log "No changes for ${target/#$HOME/~/}"
  fi
}

configure_termux_properties() {
  write_file_if_different "$TERMUX_PROPERTIES_PATH" <<'EOF_PROPERTIES'
extra-keys = [["ESC","/","-","HOME","UP","END","PGUP"],["TAB","CTRL","ALT","LEFT","DOWN","RIGHT","PGDN"]]
bell-character=ignore
terminal-margin-horizontal=4
terminal-margin-vertical=4
EOF_PROPERTIES
}

configure_termux_colors() {
  write_file_if_different "$TERMUX_COLORS_PATH" <<'EOF_COLORS'
background=#1e1e1e
foreground=#d4d4d4
color0=#1e1e1e
color1=#d16969
color2=#608b4e
color3=#d7ba7d
color4=#569cd6
color5=#c586c0
color6=#4ec9b0
color7=#d4d4d4
color8=#808080
color9=#f44747
color10=#b5cea8
color11=#ffca28
color12=#82aaff
color13=#ff78c6
color14=#89ddff
color15=#ffffff
EOF_COLORS
}

install_font() {
  mkdir -p "$(dirname "$FONT_DEST")"
  local tmp
  tmp=$(mktemp)
  if curl -fsSL "$FONT_URL" -o "$tmp"; then
    mv "$tmp" "$FONT_DEST"
    log 'Installed custom Termux font.'
  else
    rm -f "$tmp"
    warn "Failed to download font from $FONT_URL"
  fi
}

configure_shell() {
  write_file_if_different "$PROFILE_PATH" <<'EOF_PROFILE'
# ~/.profile - generated by setup_termux.sh
export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="less"
export PATH="$HOME/.local/bin:$PATH"
[ -r "$HOME/.bashrc" ] && . "$HOME/.bashrc"
EOF_PROFILE
}

configure_bash() {
  write_file_if_different "$BASHRC_PATH" <<'EOF_BASHRC'
# ~/.bashrc - generated by setup_termux.sh

# Bash completion
if [ -n "$PREFIX" ]; then
  if [ -f "$PREFIX/etc/profile.d/bash_completion.sh" ]; then
    . "$PREFIX/etc/profile.d/bash_completion.sh"
  elif [ -f "$PREFIX/share/bash-completion/bash_completion" ]; then
    . "$PREFIX/share/bash-completion/bash_completion"
  fi
fi

# Aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias gs='git status'
alias gd='git diff'
alias gl='git log --oneline -20'
alias ..='cd ..'
alias ...='cd ../..'
EOF_BASHRC
}

configure_readline() {
  write_file_if_different "$INPUTRC_PATH" <<'EOF_INPUTRC'
# ~/.inputrc - generated by setup_termux.sh
"\e[A": history-search-backward
"\e[B": history-search-forward
EOF_INPUTRC
}

configure_git() {
  local name="${USER_FULLNAME:-Your Name}"
  local email="${USER_EMAIL:-you@example.com}"

  write_file_if_different "$GITCONFIG_PATH" <<EOF_GIT
[user]
    name = $name
    email = $email
[core]
    editor = nvim
[color]
    ui = auto
[pull]
    ff = only
EOF_GIT
}

configure_ssh() {
  local ssh_user="${USER_SSH_USER:-$USER}"

  mkdir -p "$HOME/.ssh"
  chmod 700 "$HOME/.ssh"

  write_file_if_different "$SSH_CONFIG_PATH" <<EOF_SSH
# ~/.ssh/config - generated by setup_termux.sh

Host *
    User $ssh_user
    AddKeysToAgent yes
    IdentityFile ~/.ssh/id_ed25519
    IdentityFile ~/.ssh/id_rsa
    ServerAliveInterval 60
    ServerAliveCountMax 3
EOF_SSH
  chmod 600 "$SSH_CONFIG_PATH"
}

configure_tmux() {
  write_file_if_different "$TMUX_CONF_PATH" <<'EOF_TMUX'
# ~/.tmux.conf - generated by setup_termux.sh

# Change prefix from Ctrl+b to Ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Enable mouse support
set -g mouse on

# Increase scrollback history
set -g history-limit 10000

# Start window and pane numbering from 1
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows when one is closed
set -g renumber-windows on

# Split panes with | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Navigate panes with Alt+arrow keys
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Reload config with prefix+r
bind r source-file ~/.tmux.conf \; display "Config reloaded"
EOF_TMUX
}

reload_termux() {
  if command -v termux-reload-settings >/dev/null 2>&1; then
    termux-reload-settings || true
  fi
}

main() {
  require_termux
  prompt_user_info
  setup_storage
  update_system
  install_packages
  configure_shell
  configure_bash
  configure_readline
  configure_git
  configure_ssh
  configure_tmux
  configure_termux_properties
  configure_termux_colors
  install_font
  reload_termux
  log 'Termux bootstrap completed.'
}

main "$@"
